FROM paritytech/ci-linux:105b919b-20210617 as builder

WORKDIR /build

ARG FEATURES=default

COPY ./.git/ /build/.git/
COPY ./node /build/node
COPY ./pallets /build/pallets
COPY ./runtime /build/runtime
COPY ./Cargo.lock /build/Cargo.lock
COPY ./Cargo.toml /build/Cargo.toml
COPY ./scripts/test.sh /build/test.sh

CMD ["sh", "test.sh"]
