FROM paritytech/ci-linux:production

WORKDIR /var/www/trackback-node

ADD . /var/www/trackback-node

RUN rustup toolchain uninstall nightly
RUN rustup toolchain install nightly-2020-08-23
RUN rustup target add wasm32-unknown-unknown --toolchain nightly-2020-08-23

RUN bash -c "cargo build --release"


CMD ["./target/release/trackback-node", "--dev", "-lruntime=debug","--ws-external"]
